import {Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const OutfintFont = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${OutfintFont.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col  bg-slate-50 text-slate-900">
        <Navbar></Navbar>
        <main className="max-w-7xl mx-auto w-full">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
